name: push to public repo

on:
  workflow_dispatch:
  push:

jobs:
 mirror:
  runs-on: ubuntu-latest

  steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: clone
      env:
        TOKEN: ${{ secrets.PUBLIC_ORG }}
      run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@example.com"

          git remote add public https://x-access-token:$TOKEN@github.com/tme-rnd/opensource-mirror.git
          
          git push public main
        
    
    


     
