name: push to public repo

on:
  workflow_dispatch:
  ##push:
   #branches: main

jobs:
 mirror:
  runs-on: ubuntu-latest

  steps:
    - name: checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: install git filter
      run: |
        pip install git-filter-repo

    - name: remove .github
      run: |
        git filter-repo \
          --path .github \
          --invert-paths
       
    - name: git config
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"  
        
    - name: add remote
      env:
        TOKEN: ${{ secrets.PUBLIC }}
      run: |
          git remote add mirror https://x-access-token:$TOKEN@github.com/tme-xrnd/opensource-mirror_public.git
         
    - name: push
      run: |
          git push mirror HEAD:main --force 
